import { useState } from "react";
import { Screen, UserRole } from "../App";
interface Props { navigate: (screen: Screen, extras?: any) => void; role: UserRole; }
const conversations = [
  { name: "LabTech UFMG", initials: "LT", topic: "Desenvolvedor Front-end React", preview: "Olá, Mariana! Gostamos muito do seu portfólio.", time: "10:32", unread: 2 },
  { name: "EJ Consulting", initials: "EJ", topic: "Analista de Dados", preview: "Combinado, vamos alinhar o início do projeto.", time: "Ontem", unread: 0 },
];
export default function Messages({ navigate, role }: Props) {
 const [text, setText] = useState(""); const [messages, setMessages] = useState([{ own:false, text:"Olá, Mariana! Gostamos muito do seu portfólio e queremos conversar sobre o projeto.", time:"10:28" }, { own:true, text:"Que ótima notícia! Tenho bastante interesse e disponibilidade para conversarmos.", time:"10:30" }]);
 const send = () => { if (!text.trim()) return; setMessages([...messages, { own:true, text, time:"agora" }]); setText(""); };
 return <div className="max-w-6xl mx-auto px-6 py-10"><div className="mb-8"><p className="text-xs font-medium text-emerald-600 uppercase tracking-wide">Conexões</p><h1 className="text-3xl text-gray-900 mt-1" style={{fontFamily:"'Instrument Serif', serif"}}>Mensagens</h1></div><div className="grid md:grid-cols-[290px_1fr] min-h-[560px] border border-gray-100 rounded-2xl overflow-hidden bg-white">
  <aside className="border-r border-gray-100"><div className="p-4 border-b border-gray-100"><input placeholder="Buscar conversa" className="w-full bg-gray-50 rounded-lg px-3 py-2 text-xs outline-none" /></div>{conversations.map((c, i) => <button key={c.name} className={`w-full p-4 text-left flex gap-3 border-b border-gray-50 hover:bg-gray-50 ${i === 0 ? "bg-emerald-50/50" : ""}`}><span className="w-10 h-10 rounded-xl bg-emerald-100 text-emerald-700 flex items-center justify-center text-xs font-semibold">{c.initials}</span><span className="min-w-0 flex-1"><span className="flex justify-between gap-2"><strong className="text-sm text-gray-800 truncate">{c.name}</strong><small className="text-[10px] text-gray-400">{c.time}</small></span><span className="block text-xs text-gray-400 mt-0.5 truncate">{c.preview}</span></span>{c.unread > 0 && <span className="self-center w-5 h-5 rounded-full bg-emerald-600 text-white text-[10px] flex items-center justify-center">{c.unread}</span>}</button>)}</aside>
  <section className="flex flex-col"><header className="p-4 border-b border-gray-100 flex items-center gap-3"><span className="w-10 h-10 rounded-xl bg-emerald-100 text-emerald-700 flex items-center justify-center text-xs font-semibold">LT</span><div><p className="text-sm font-semibold">LabTech UFMG</p><p className="text-xs text-emerald-600">Desenvolvedor Front-end React</p></div><button onClick={() => navigate(role === "org" ? "org-panel" : "application-status")} className="ml-auto text-xs text-gray-500 hover:text-emerald-700">{role === "org" ? "← Voltar ao painel" : "Ver candidatura →"}</button></header><div className="flex-1 p-5 space-y-4 bg-[#fcfdfc]">{messages.map((m, i) => <div key={i} className={`flex ${m.own ? "justify-end" : "justify-start"}`}><div className={`max-w-[75%] rounded-2xl px-4 py-3 text-sm ${m.own ? "bg-emerald-600 text-white rounded-br-sm" : "bg-white border border-gray-100 text-gray-600 rounded-bl-sm"}`}><p>{m.text}</p><small className={`block text-[10px] mt-1 ${m.own ? "text-emerald-100" : "text-gray-400"}`}>{m.time}</small></div></div>)}</div><form onSubmit={(e)=>{e.preventDefault();send();}} className="p-4 border-t border-gray-100 flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Escreva uma mensagem..." className="flex-1 rounded-xl border border-gray-200 px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-emerald-200"/><button className="rounded-xl bg-emerald-600 px-4 text-white text-sm font-medium">Enviar</button></form></section>
 </div></div>;
}
